version: "3"
services:
  dnf-repo:
    build:
      context: .
      dockerfile: dnf.dockerfile
    volumes:
      - "dnf-repo:/tmp/dnf"
    stdin_open: true
    tty: true

  apt-repo:
    build:
      context: .
      dockerfile: apt.dockerfile
    volumes:
      - "apt-repo:/tmp/.aptly"
    stdin_open: true
    tty: true

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    volumes:
      - "apt-repo:/usr/share/nginx/html/apt"
      - "dnf-repo:/usr/share/nginx/html/dnf"
    depends_on:
      - dnf-repo
      - apt-repo

volumes:
  dnf-repo:
  apt-repo:

